name = "undercover-worker"
main = "src/index.ts"
compatibility_date = "2024-12-05"
workers_dev = true

routes = [
  { pattern = "undercover.dengjiabei.cn/api/*", zone_name = "dengjiabei.cn" }
]

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]
